apiVersion: v1
kind: PersistentVolume
metadata:
  name: golang-crud-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/golang-crud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golang-crud-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
