apiVersion: v1
kind: Service
metadata:
  name: golang-crud
spec:
  selector:
    app: golang-crud
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort  # This makes the service accessible outside the cluster
